# Generated by Django 5.0 on 2023-12-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='categeory',
            new_name='category',
        ),
    ]
